config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  resources :events
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :description, presence: true
  validates :starting_date, presence: true, future_date: true
  validates :ending_date, presence: true

  validate :ending_date_after_starting_date

  before_validation :normalize_name

  # Scopes
  scope :in_past_month, -> { where(ending_date: 1.month.ago..1.day.ago) }
  scope :with_concert_word, -> { where("description LIKE '%concert%'") }

  private

  def ending_date_after_starting_date
    ending_date = self.ending_date || Time.now
    starting_date = self.starting_date || Time.now
    errors.add(:ending_date, :after_starting_date) if ending_date < starting_date
  end

  def normalize_name
    self.name = self.name.strip.titleize if self.name.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :username ])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
    @events_in_past_month = Event.in_past_month
    @events_with_concert_word = Event.with_concert_word
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy!

    respond_to do |format|
      format.html { redirect_to events_path, status: :see_other, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :description, :starting_date, :ending_date)
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [ :update ]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [ :avatar ])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<tr id="<%= dom_id event %>" class="hover:bg-gray-100 dark:hover:bg-neutral-700">
  <td class="whitespace-nowrap text-sm font-medium text-gray-800 dark:text-neutral-200"><%= link_to event.name, event, class: "w-full px-6 py-4 inline-block hover:underline focus:outline-none focus:underline" %></td>
  <td class="px-6 py-4 min-w-52 max-w-64 text-sm text-gray-800 dark:text-neutral-200"><%= event.description %></td>
  <td class="px-6 py-4 min-w-52 max-w-64 text-sm text-gray-800 dark:text-neutral-200"><%= event.user.username %></td>
  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-800 dark:text-neutral-200"><%= event.starting_date.strftime("%B %d, %Y - %I:%M %P") %></td>
  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-800 dark:text-neutral-200"><%= event.ending_date.strftime("%B %d, %Y - %I:%M %P") %></td>
</tr>

app/views/events/_form.html.erb
<%= form_with(model: event, class: "grid gap-4") do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="max-w-sm">
    <%= form.label :name, class: "block text-sm font-medium mb-2 dark:text-white" %>
    <%= form.text_field :name, placeholder: "you@site.com", required: true, autocomplete: "on", class: "py-3 px-4 block w-full border-gray-200 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-neutral-900 dark:border-neutral-700 dark:text-neutral-400 dark:placeholder-neutral-500 dark:focus:ring-neutral-600" %>
  </div>

  <div class="max-w-sm">
    <%= form.label :description, class: "block text-sm font-medium mb-2 dark:text-white" %>
    <%= form.text_area :description, class: "py-3 px-4 block w-full border-gray-200 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-neutral-900 dark:border-neutral-700 dark:text-neutral-400 dark:placeholder-neutral-500 dark:focus:ring-neutral-600" %>
  </div>

  <div class="max-w-sm">
    <%= form.label :starting_date, style: "display: block" %>
    <%= form.datetime_field :starting_date, required: true, class: "py-3 px-4 block w-full border-gray-200 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-neutral-900 dark:border-neutral-700 dark:text-neutral-400 dark:placeholder-neutral-500 dark:focus:ring-neutral-600" %>
  </div>

  <div class="max-w-sm">
    <%= form.label :ending_date, style: "display: block" %>
    <%= form.datetime_field :ending_date, required: true, class: "py-3 px-4 block w-full border-gray-200 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-neutral-900 dark:border-neutral-700 dark:text-neutral-400 dark:placeholder-neutral-500 dark:focus:ring-neutral-600" %>
  </div>

  <div class="max-w-sm">
    <%= form.submit class: "py-3 px-4 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 focus:outline-none focus:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<main class="container mx-auto p-4">
  <% content_for :title, "Editing event" %>

  <%= link_to "Back to events", events_path, class: "py-3 px-4 mb-4 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-transparent text-blue-600 hover:bg-blue-100 hover:text-blue-800 focus:outline-none focus:bg-blue-100 focus:text-blue-800 disabled:opacity-50 disabled:pointer-events-none dark:text-blue-500 dark:hover:bg-blue-800/30 dark:hover:text-blue-400 dark:focus:bg-blue-800/30 dark:focus:text-blue-400" %>

  <h1 class="text-4xl mb-4">Editing event</h1>
  <%= render "form", event: @event %>

</main>

app/views/events/index.html.erb
<main class="container mx-auto p-4">
  <%= render "partials/flash" %>

  <% content_for :title, "Events" %>

  <div class="flex justify-between items-center mb-4">
    <h1 class="text-4xl">Eventos</h1>
    <%= link_to "New event", new_event_path, class: "py-3 px-4 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-transparent text-blue-600 hover:bg-blue-100 hover:text-blue-800 focus:outline-none focus:bg-blue-100 focus:text-blue-800 disabled:opacity-50 disabled:pointer-events-none dark:text-blue-500 dark:hover:bg-blue-800/30 dark:hover:text-blue-400 dark:focus:bg-blue-800/30 dark:focus:text-blue-400" %>
  </div>

  <div class="flex flex-col">
    <div class="-m-1.5 overflow-x-auto">
      <div class="p-1.5 min-w-full inline-block align-middle">
        <div class="overflow-hidden">
          <table class="min-w-full divide-y divide-gray-200 dark:divide-neutral-700" id="events">
            <thead>
              <tr>
                <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Nombre</th>
                <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Descripción</th>
                <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Anfitrión</th>
                <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Inicio</th>
                <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Fin</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 dark:divide-neutral-700">
              <% @events.each do |event| %>
                <%= render event %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <hr class="my-8">

  <h2 class="text-3xl mb-4">Eventos en el último mes</h2>
  <% if @events_in_past_month.empty? %>
    <p>No hay eventos programados en el último mes.</p>
  <% else %>
    <div class="flex flex-col">
      <div class="-m-1.5 overflow-x-auto">
        <div class="p-1.5 min-w-full inline-block align-middle">
          <div class="overflow-hidden">
            <table class="min-w-full divide-y divide-gray-200 dark:divide-neutral-700" id="events">
              <thead>
                <tr>
                  <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Nombre</th>
                  <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Descripción</th>
                  <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Anfitrión</th>
                  <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Inicio</th>
                  <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Fin</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-gray-200 dark:divide-neutral-700">
                <% @events_in_past_month.each do |event| %>
                  <%= render event %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <hr class="my-8">

  <h2 class="text-3xl mb-4">Eventos filtrados por: 'concert'</h2>
  <% if @events_with_concert_word.empty? %>
    <p>No hay eventos con la palabra 'concert'.</p>
  <% else %>
    <div class="flex flex-col">
      <div class="-m-1.5 overflow-x-auto">
        <div class="p-1.5 min-w-full inline-block align-middle">
          <div class="overflow-hidden">
            <table class="min-w-full divide-y divide-gray-200 dark:divide-neutral-700" id="events">
              <thead>
                <tr>
                  <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Nombre</th>
                  <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Descripción</th>
                  <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Anfitrión</th>
                  <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Inicio</th>
                  <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase dark:text-neutral-500">Fin</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-gray-200 dark:divide-neutral-700">
                <% @events_with_concert_word.each do |event| %>
                  <%= render event %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  <% end %>

</main>

app/views/events/new.html.erb
<main class="container mx-auto p-4 main-min-h">
  <% content_for :title, "New event" %>

  <%= link_to "Back to events", events_path, class: "py-3 px-4 mb-4 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-transparent text-blue-600 hover:bg-blue-100 hover:text-blue-800 focus:outline-none focus:bg-blue-100 focus:text-blue-800 disabled:opacity-50 disabled:pointer-events-none dark:text-blue-500 dark:hover:bg-blue-800/30 dark:hover:text-blue-400 dark:focus:bg-blue-800/30 dark:focus:text-blue-400" %>

  <h1 class="text-4xl mb-4">New event</h1>

  <%= render "form", event: @event %>

</main>

app/views/events/show.html.erb
<main class="container mx-auto p-4">
  <p style="color: green"><%= notice %></p>

  <%= link_to "Back to events", events_path, class: "py-3 px-4 mb-4 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-transparent text-blue-600 hover:bg-blue-100 hover:text-blue-800 focus:outline-none focus:bg-blue-100 focus:text-blue-800 disabled:opacity-50 disabled:pointer-events-none dark:text-blue-500 dark:hover:bg-blue-800/30 dark:hover:text-blue-400 dark:focus:bg-blue-800/30 dark:focus:text-blue-400" %>
  <article class="relative space-y-4">
    <p><small><%= @event.starting_date.strftime("%A, %B %e (%I:%M %P)") %> -> <%= @event.ending_date.strftime("%A, %B %e (%I:%M %P)") %> </small></p>

    <div class="flex justify-between">
      <h2 class="text-4xl"><%= @event.name %></h2>
      <div class="flex gap-2">
        <%= link_to edit_event_path(@event), class: "py-3 px-4 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-blue-600 text-blue-600 hover:border-blue-500 hover:text-blue-500 focus:outline-none focus:border-blue-500 focus:text-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:border-blue-500 dark:text-blue-500 dark:hover:text-blue-400 dark:hover:border-blue-400" do %>
          <span class="sr-only">Editar</span>
          <svg xmlns="http://www.w3.org/2000/svg" class="w-4" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" /><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1l1-4z" /></g></svg>
        <% end %>
        <%= button_to event_path(@event), method: :delete, class: "py-3 px-4 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-transparent bg-red-500 text-white hover:bg-red-600 focus:outline-none focus:bg-red-600 disabled:opacity-50 disabled:pointer-events-none" do %>
          <span class="sr-only">Eliminar</span>
          <svg xmlns="http://www.w3.org/2000/svg" class="w-4" viewBox="0 0 2048 2048"><path fill="currentColor" d="M1792 384h-128v1472q0 40-15 75t-41 61t-61 41t-75 15H448q-40 0-75-15t-61-41t-41-61t-15-75V384H128V256h512V128q0-27 10-50t27-40t41-28t50-10h384q27 0 50 10t40 27t28 41t10 50v128h512zM768 256h384V128H768zm768 128H384v1472q0 26 19 45t45 19h1024q26 0 45-19t19-45zM768 1664H640V640h128zm256 0H896V640h128zm256 0h-128V640h128z" /></svg>
        <% end %>
      </div>
    </div>
    <p><%= @event.description %> </p>
    <p class="bg-gray-100 border border-gray-200 text-gray-800 rounded-lg p-4 md:p-5 dark:bg-white/10 dark:border-white/20 dark:text-white">
      Por <strong><%= @event.user.username %> </strong>
    </p>
  </article>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Tickevents" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/partials/_flash.html.erb
<% if notice || alert %>
  <p class="text-green-600"><%= notice %></p>
  <p class="text-red-500"><%= alert %></p>
<% end %>

app/views/partials/_header.html.erb
<header class="min-h-16 py-4 sticky top-0 bg-gray-50/80 dark:bg-gray-800/80 backdrop-blur-sm">
  <div class="container mx-auto px-4 flex items-baseline justify-between">
    <%= link_to root_path, class: "font-bold text-2xl" do %>
      <h1>Tickevents</h1>
    <% end %>
    <% if user_signed_in? %>
      <div class="flex gap-5 items-center">
        <%= link_to edit_user_registration_path(current_user), class: "flex gap-2 items-center" do %>
          <p><%= current_user.username %></p>
          <% if current_user.avatar.attached? %>
            <picture class="size-10 rounded-full shadow-sm border border-gray-200 overflow-hidden"><img src="<%= url_for(current_user.avatar) %>" alt="Avatar" class="w-10"></picture>
          <% else %>
            <span>No avatar</span>
          <% end %>
        <% end %>
        <%= button_to destroy_user_session_path, method: :delete, class: "py-3 px-3 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 focus:outline-none focus:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none dark:bg-neutral-800 dark:border-neutral-700 dark:text-white dark:hover:bg-neutral-700 dark:focus:bg-neutral-700" do %>
          <span class="sr-only">Cerrar sesión</span>
          <svg xmlns="http://www.w3.org/2000/svg" class="w-4" viewBox="0 0 24 24"><path fill="currentColor" d="M4 5.4A1.4 1.4 0 0 1 5.4 4h6.2A1.4 1.4 0 0 1 13 5.4V8a1 1 0 1 0 2 0V5.4A3.4 3.4 0 0 0 11.6 2H5.4A3.4 3.4 0 0 0 2 5.4v13.2A3.4 3.4 0 0 0 5.4 22h6.2a3.4 3.4 0 0 0 3.4-3.4V16a1 1 0 1 0-2 0v2.6a1.4 1.4 0 0 1-1.4 1.4H5.4A1.4 1.4 0 0 1 4 18.6z" /><path fill="currentColor" d="M17.293 8.293a1 1 0 0 1 1.414 0l3 3a1 1 0 0 1 0 1.414l-3 3a1 1 0 0 1-1.414-1.414L18.586 13H7a1 1 0 1 1 0-2h11.586l-1.293-1.293a1 1 0 0 1 0-1.414" /></svg>
        <% end %>
      </div>
    <% else %>
      <%= link_to "Ingresar", new_user_session_path %>
    <% end %>
  </div>
</header>